<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Update="video to audio %28to m4a%29.bat">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>

	  <None Update="*.bat">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="*.exe">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>  
  </ItemGroup>

</Project>
